name: EKS-Terraform-Vuln-Check
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  vuln-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=bitra-devops_portfolio-webapp-code
            -Dsonar.organization=santosh-bitra
            -Dsonar.sources=.
#            -Dsonar.java.binaries=.
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}